name: Continuous Integration (CI)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  validate:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Linter
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test
        env:
          STAGE: dev

      - name: Build Project
        run: yarn build
